### PR TITLE
docs for em static mode

### PR DESCRIPTION
**Pull request by bverbeken**

### CODE REVIEW

**Comment by bverbeken** [comment]
@PabloNeirotti how did you create the screenshot for EM select mode? I'd like to use the same chart, but on my machine it looks like this 😅
Screenshot 2021-11-29 at 20 06 19

**Comment by PabloNeirotti** [comment]
Ehh it's the small theatre one in the test studio 😅 does it not look like that to you?

**Comment by PabloNeirotti** [comment]
Here's a freebie with a similar size.

Screen Shot 2021-11-29 at 9 08 19 PM

**Comment by PabloNeirotti** [comment]
Bonus with tooltip 😄 

Screen Shot 2021-11-29 at 9 10 04 PM

**Comment by bverbeken** [comment]
Thank you so much :)

**Review by mroloux — APPROVED** [review]

**Review by PabloNeirotti — APPROVED** [review]

**Pull request merged**
