### PR TITLE
Docs facelift

### PR DESCRIPTION
**Pull request by PabloNeirotti**
This PR:
- Reorganizes the Renderer tab sidebar to make it easier to find things, and to make it easier to discover features.
- Adds dark mode (needed some tweaks so it looks nice).
- Changes to the "How to embed the Renderer" page.
- Several minor tweaks, maybe an extra image here or there, I lost track.

Screen Shot 2021-12-10 at 3 32 34 PM

Try it out and let me know primarily if you think the sidebar is okay.

BTW, the "Advanced" tab really stands for "things you probably don't kneed or should really know what you are doing", we could rename it. Correct me if I'm wrong about putting these settings in there as well 😄

### CODE REVIEW

**Comment by PabloNeirotti** [comment]
Ah P.S: There is a ton more to work on, like the First time tutorial we mentioned and other details. I wanted to do a first pass just for discoverability (but as you can see I already got sidetracked) and once I update the website with the "Learning hub" go back to this.

**Comment by PabloNeirotti** [comment]
[Docs facelift: Episode 1](https://trello.com/c/ijU1MZ3N/4585-docs-facelift-episode-1)

**Comment by bverbeken** [comment]
Like! 👍

Some suggestions (just small things I noticed, and I did not re-read _all_ pages haha)
 
* I would move ticketListings to the advanced category. That's really a specific thing built for a no-longer-target-type-of-customer (secondary market). And the "pricing" category is something *everyone* will see :) 

* http://localhost:3000/docs/renderer/config-cursortooltip can be removed altogether imho

* on the minimum requirements page (http://localhost:3000/docs/renderer/configure-your-floor-plan) you say 
**divId (or container)**, but only mention **event**. That should be **event (or events)** for completeness

**Comment by mroloux** [comment]
@PabloNeirotti this is what I get when I run `yarn start`. Am I doing something wrong?

Screenshot 2021-12-13 at 09 38 24

**Comment by mroloux** [comment]
+1 for creating this grouping, it looks much cleaner than having a wall of properties 😆 

Some thoughts:

- Would it be a good idea to highlight the most commonly used settings somehow? E.g. almost every customer will want to use the `session` parameter, but right now that's tucked away under 'Session'. Same for `pricing` and `priceFormatter`. And right now some less important (advanced?) parameters are under 'fundamentals', e.g. `mode`, `channels` and `activeFloor`.
- `Object overrides` feels more natural to me than `Object overwrites` - as in "you can override some of the default behaviour for objects".

**Comment by bverbeken** [comment]
> @PabloNeirotti this is what I get when I run `yarn start`. Am I doing something wrong?
> 
> Screenshot 2021-12-13 at 09 38 24
> 
> (the rest of the pages seem to work btw)

@mroloux that's normal. 
There's an index.html page that redirects to /docs/index.html (client side)
This index.html page gets picked up by github pages automatically. But not on localhost.

**Comment by PabloNeirotti** [comment]
Cool 😄 

@bverbeken 

- ticketListings: Yeah I'm like, this is really gonna expose this feature now 😄 Moved it to Advanced.
- cursorTooltip removed.
- The "Minimum requirements" page was already there, I just renamed the title, but I didn't make changes to it. In fact I kinda wanted to nuke it, we already have a "how to embed" page anyways, and the chart will throw an error if you don't do it right. Thoughts?

@mroloux 

- I don't see that as an issue, pricing and session are both top level, but as categories. It's still the first item on each case so that's where to start from (and not, say, showSectionPricingOverlay). If we start to pull them out of there we will loose the whole benefit of grouping and go back to square one. The whole point of grouping was so that the popular settings bring the traffic and they can discover the less popular settings.
- Ah yes overrides is the word I actually wanted to go for. Fixed 😄

**Comment by mroloux** [comment]
Ok, but I would still move `channels` and `activeFloor` out of the 'fundamentals' category, they seem out of place there.

And maybe the `Session` category could go higher in the menu, e.g. after pricing?

**Comment by bverbeken** [comment]
> * nuke it

Go 👍

**Comment by PabloNeirotti** [comment]
@mroloux  Oh yea. Where should we put `channels` and `activeFloor` ? Channels is pretty important, but active floor is very specific.

**Comment by mroloux** [comment]
Ok, let's just move `activeFloor` then - maybe `Visibility` is a good place? Since it influences the visibility of the floors.

**Comment by PabloNeirotti** [comment]
Oh actually those two settings are there because I didn't know where to put them.

What I meant with Channels being pretty important, is that it could be an item on the sidebar that lacks sub-items. It might feel weird as a one off but hey 😄 Or have a Channels category with just `channels` inside. I see this alongside Pricing and Categories tbh.

As for Active floor, I feel it's just a "startup setting" because you can just undo it after one click. I don't think it's advanced or "something you shouldn't use", but also not a fundamental either 🤔 ...

**Comment by mroloux** [comment]
Yeah, I think `Channels` might deserve it's own top-level item 👍

**Comment by PabloNeirotti** [comment]
Alrighty Channels is now a top level item.

I think this should be good for a first iteration, but do let me know.

**Review by bverbeken — APPROVED** [review]

**Pull request merged**
